export const ADD_PRODUCT = 'ADD_PRODUCT'
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR'

export const START_DOWNLOAD = 'START_DOWNLOAD'
export const START_DOWNLOAD_SUCCESS = 'START_DOWNLOAD_SUCCESS'
export const START_DOWNLOAD_ERROR = 'START_DOWNLOAD_ERROR'